### ISSUE TITLE
Upgrade to uglifyjs 1.3.5 because 1.2.5 is buggy

### ISSUE THREAD

**Issue by nitinsurana** [requirejs/r.js#903] opened 2016-03-15 13:00 UTC
Hi,

UglifyJs 1.2.5 minifies something like below

```((_ref = ace.require) != null ? _ref : require)("ace/range").Range;```

to

```
(c=ace.require)!=null?c:require("ace/range").Range
```

**Comment by jrburke** [comment] 2016-03-15 16:30
What version of r.js are you using? It sounds like an older one. It is best if it can be upgraded to the latest r.js release, it has [an option for Uglify 2](https://github.com/requirejs/r.js/blob/33799fa3d5f874c1b50f460cdaa8581f409698b8/build/example.build.js#L99), which is getting much more development focus by that team than Uglify 1.

I also plan on switching the default optimize: 'uglify' option to use Uglify 2, tracking that in #883, so I will close this bug as a duplicate of #883.

**Closed by jrburke** 2016-03-15 16:30 UTC
