### ISSUE TITLE
Add some error message on scripts timeout error

### ISSUE THREAD

**Issue by ncrypthic** [requirejs/r.js#893] opened 2016-02-11 05:56 UTC
Hi,

When optimization runs, suddenly it throws vague error message.

```sh
Tracing dependencies for: ../main
Error: Error: Module loading did not complete for: ../main, dashboard/app, ckeditor at
Function.build.checkForErrors (/home/ncrypthic/workspace/demo/node_modules/requirejs/bin/r.js:31556:19)
```

After digging around I found that during loading some script files hit requirejs default waiting time (7s). But the error message doesn't say this. Could you add some error message for timed out script files?

Thank you,
Lim

**Comment by ncrypthic** [comment] 2016-02-11 06:01
This is what I found:

```js
// r.js
31531         if (errIds.length || failedPluginIds.length) {
31532             if (failedPluginIds.length) {
31533                 errMessage += 'Loader plugin' +
31534                     (failedPluginIds.length === 1 ? '' : 's') +
31535                     ' did not call ' +
31536                     'the load callback in the build:\n' +
31537                     failedPluginIds.map(function (pluginId) {
31538                         var pluginResources = failedPluginMap[pluginId];
31539                         return pluginId + ':\n  ' + pluginResources.join('\n  ');
31540                     }).join('\n') + '\n';
31541             }
31542             errMessage += 'Module loading did not complete for: ' + errIds.join(', ');
31543 
31544             if (hasErrUrl) {
31545                 errMessage += '\nThe following modules share the same URL. This ' +
31546                               'could be a misconfiguration if that URL only has ' +
31547                               'one anonymous module in it:';
31548                 for (prop in errUrlConflicts) {
31549                     if (hasProp(errUrlConflicts, prop)) {
31550                         errMessage += '\n' + prop + ': ' +
31551                                       errUrlConflicts[prop].join(', ');
31552                     }
31553                 }
31554             }
31555             throw new Error(errMessage);
31556         }
```
My scripts don't hit 31532 & 31544, so the error message only displays 31542 without additional information about timeout.

Hope it helps

**Comment by jrburke** [comment] 2016-03-10 02:50
I will use ##863 to fix this, probably by setting waitSeconds to 0 while in build mode. So closing this as a duplicate of that bug.

**Closed by jrburke** 2016-03-10 02:50 UTC
