### ISSUE TITLE
es7 async await 

### ISSUE THREAD

**Issue by gunins** [requirejs/r.js#957] opened 2017-03-28 10:21 UTC
Hi
I added es7 async function(){ let a = await b() } in to my define module. r.js throwing error after `Error: Line 16: Unexpected identifier`

Do you have any plans to support async generators in r.js https://jakearchibald.com/2014/es7-async-functions/

**Comment by marcoscaceres** [comment] 2017-07-19 08:27
duplicate of https://github.com/requirejs/r.js/issues/959

**Comment by jrburke** [comment] 2017-07-30 21:45
As of r.js 2.3.4, the version of esprima that should understand async syntax, this will allows r.js to construct a combined, unminified file. The other part is using a version of uglify-js that understands async syntax. #959 has some background on this, but best to set `optimize: 'none'` in the r.js config, and then use the uglify-es or some ES5+ aware minifier as a separate, post r.js, build step.

Closing this as basic support is in, with the minify step tracked/discussed in #959.

**Closed by jrburke** 2017-07-30 21:45 UTC
